const ACHIEVEMENT_KEYS = {
  COMPLETE_TUTORIAL: "COMPLETE_TUTORIAL",
  ADD_FIRST_MISSION: "ADD_FIRST_MISSION",
  COMPLETE_FIRST_MISSION: "COMPLETE_FIRST_MISSION",
  COMPLETE_PROFILE: "COMPLETE_PROFILE",
  COMPLETE_DAILY_MISSION: "COMPLETE_DAILY_MISSION",
  COMPLETE_DROP_OF_SWEAT_MISSION: "COMPLETE_DROP_OF_SWEAT_MISSION",
  COMPLETE_CHALLENGING_MISSION: "COMPLETE_CHALLENGING_MISSION",
  COMPLETE_LIFE_HACKER_MISSION: "COMPLETE_LIFE_HACKER_MISSION",
  COMPLETE_ANTI_PROCRASTINATOR_MISSION: "COMPLETE_ANTI_PROCRASTINATOR_MISSION",
  COMPLETE_ALL_DIFFICULTY_LEVELS: "COMPLETE_ALL_DIFFICULTY_LEVELS",
  GIVE_UP_WITH_SUBTASK: "GIVE_UP_WITH_SUBTASK",
  COMPLETE_5_MISSIONS: "COMPLETE_5_MISSIONS",
  COMPLETE_10_MISSIONS: "COMPLETE_10_MISSIONS",
  COMPLETE_25_MISSIONS: "COMPLETE_25_MISSIONS",
  COMPLETE_50_MISSIONS: "COMPLETE_50_MISSIONS",
  REACH_LEVEL_5: "REACH_LEVEL_5",
  REACH_LEVEL_10: "REACH_LEVEL_10",
  REACH_LEVEL_25: "REACH_LEVEL_25",
  REACH_LEVEL_50: "REACH_LEVEL_50",
  UNLOCK_ALL_ACHIEVEMENTS: "UNLOCK_ALL_ACHIEVEMENTS",
};

export default ACHIEVEMENT_KEYS;
